package project.quiz.maker;

import java.awt.event.ItemEvent;
import java.util.LinkedHashMap;
import java.util.Map;
import javax.swing.JComboBox;

public final class DialogChooseCollection extends javax.swing.JDialog {

    private final CollectionData collectionData = CollectionData.createInstance ();
    
    private final static String MESSAGE_EMPTY_COLLECTION = "The selected collection is empty!";
    
    private FormMain formMain;
    private FormTakeQuiz formTakeQuiz;
    
    private Map<Integer, Collection> map;
    private User loggedUser;
    private Collection selectedCollection;
    private boolean hasSelectedCollection;
    
    private JComboBox comboBoxCollectionID = null;

    public DialogChooseCollection ( java.awt.Frame parent, boolean modal ) {
        super (parent, modal);
        initComponents ();

        this.comboBoxCollectionID = new JComboBox ();

        setMapData ();
        setComboCollection ();
    }
    
    public DialogChooseCollection ( java.awt.Frame parent, boolean modal, FormMain formMain ) {
        this (parent, modal);
        
        this.formMain = formMain;
        this.loggedUser = formMain.getLoggUser ();
    }
    
    public void setMapData () {
        collectionData.hasFileExisted ();

        map = (LinkedHashMap<Integer, Collection>) collectionData.fetchMapData ();
    }

    public void setComboCollection () {
        // clean the combobox
        comboBoxCollectionID.removeAllItems ();
        comboBox_collection.removeAllItems ();

        // add new data to combobox
        map.entrySet ().forEach ((entry) -> {
            Integer key = entry.getKey ();
            Collection value = entry.getValue ();

            comboBoxCollectionID.addItem (key);
            comboBox_collection.addItem (value.getCollectionName ());
        });
    }

    public boolean hasSelectedCollection () {
        return selectedCollection != null;
    }

    public Collection getSelectedCollection () {
        return selectedCollection;
    }

    public void deSelectedCollection () {
        selectedCollection = null;
    }

    private void setSelectedCollection () {
        int selectedIndex = comboBox_collection.getSelectedIndex ();
        comboBoxCollectionID.setSelectedIndex (selectedIndex);
        int selectedID = (int) comboBoxCollectionID.getSelectedItem ();

        if ( !VerifyVariable.isNull (selectedID) ) {
            boolean isContained = map.containsKey (selectedID);

            if ( isContained ) {
                selectedCollection = map.get (selectedID);
            }
        }
    }

    public void setFormTakeQuizClosed() {
        this.formTakeQuiz = null;
    }
    
    public void setDialogChooseCollectionClosed() {
        this.formMain.setDialogChooseCollectionClosed ();
    }
    
    public void updateFormMainData(User loggedUser) {
        formMain.setLoggedUser (loggedUser);
        formMain.setDialogChooseCollectionClosed ();
    }
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_background = new javax.swing.JPanel();
        panel_header = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        label_title = new javax.swing.JLabel();
        button_choose = new javax.swing.JButton();
        comboBox_collection = new javax.swing.JComboBox<>();
        panel_paddingLeft = new javax.swing.JPanel();
        panel_paddingRight = new javax.swing.JPanel();
        panel_paddingTop = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CHOOSE A COLLECTION");
        setAlwaysOnTop(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        panel_background.setBackground(new java.awt.Color(255, 255, 255));

        panel_header.setBackground(new java.awt.Color(20, 10, 37));
        panel_header.setPreferredSize(new java.awt.Dimension(500, 100));

        jPanel1.setBackground(new java.awt.Color(20, 10, 37));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(20, 10, 37));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        label_title.setFont(new java.awt.Font("Bahnschrift", 0, 36)); // NOI18N
        label_title.setForeground(new java.awt.Color(255, 255, 255));
        label_title.setText("CHOOSE A COLLECTION");

        javax.swing.GroupLayout panel_headerLayout = new javax.swing.GroupLayout(panel_header);
        panel_header.setLayout(panel_headerLayout);
        panel_headerLayout.setHorizontalGroup(
            panel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_headerLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_title, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panel_headerLayout.setVerticalGroup(
            panel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_headerLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_title, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        button_choose.setUI(new jbuttoncss.CSSButton());
        button_choose.setBackground(new java.awt.Color(219, 43, 48));
        button_choose.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        button_choose.setForeground(new java.awt.Color(255, 255, 255));
        button_choose.setText("CHOOSE");
        button_choose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_chooseActionPerformed(evt);
            }
        });

        comboBox_collection.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        comboBox_collection.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboBox_collectionItemStateChanged(evt);
            }
        });

        panel_paddingLeft.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panel_paddingLeftLayout = new javax.swing.GroupLayout(panel_paddingLeft);
        panel_paddingLeft.setLayout(panel_paddingLeftLayout);
        panel_paddingLeftLayout.setHorizontalGroup(
            panel_paddingLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );
        panel_paddingLeftLayout.setVerticalGroup(
            panel_paddingLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panel_paddingRight.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panel_paddingRightLayout = new javax.swing.GroupLayout(panel_paddingRight);
        panel_paddingRight.setLayout(panel_paddingRightLayout);
        panel_paddingRightLayout.setHorizontalGroup(
            panel_paddingRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );
        panel_paddingRightLayout.setVerticalGroup(
            panel_paddingRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panel_paddingTop.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panel_paddingTopLayout = new javax.swing.GroupLayout(panel_paddingTop);
        panel_paddingTop.setLayout(panel_paddingTopLayout);
        panel_paddingTopLayout.setHorizontalGroup(
            panel_paddingTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panel_paddingTopLayout.setVerticalGroup(
            panel_paddingTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panel_backgroundLayout = new javax.swing.GroupLayout(panel_background);
        panel_background.setLayout(panel_backgroundLayout);
        panel_backgroundLayout.setHorizontalGroup(
            panel_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_header, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
            .addGroup(panel_backgroundLayout.createSequentialGroup()
                .addComponent(panel_paddingLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_paddingTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboBox_collection, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(button_choose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_paddingRight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panel_backgroundLayout.setVerticalGroup(
            panel_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_backgroundLayout.createSequentialGroup()
                .addComponent(panel_header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_paddingLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_paddingRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_backgroundLayout.createSequentialGroup()
                        .addComponent(panel_paddingTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboBox_collection, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(button_choose, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(35, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panel_background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 265, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panel_background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void button_chooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_chooseActionPerformed
        hasSelectedCollection = true;
        
        if(!VerifyVariable.hasFormOpened (formTakeQuiz)) {
            boolean isEmptyCollection = selectedCollection.getQuestionList ().isEmpty ();
                    
            if(!isEmptyCollection) {
                formTakeQuiz = new FormTakeQuiz (this, selectedCollection);
                formTakeQuiz.setLoggedUser (loggedUser);
                formTakeQuiz.setVisible (true);
            }
            else {
                formMain.setDialogChooseCollectionClosed ();
                MessageBox.showMessage (null, MESSAGE_EMPTY_COLLECTION);           
            }
        }
        
        this.dispose ();
    }//GEN-LAST:event_button_chooseActionPerformed

    private void comboBox_collectionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboBox_collectionItemStateChanged
        if ( evt.getStateChange () == ItemEvent.SELECTED ) {
            deSelectedCollection ();
            setSelectedCollection ();
        }
    }//GEN-LAST:event_comboBox_collectionItemStateChanged

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if ( !hasSelectedCollection ) {
            selectedCollection = null;
        }
         
        if (VerifyVariable.hasFormOpened (formMain)) {
            formMain.setDialogChooseCollectionClosed ();
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main ( String args[] ) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for ( javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels () ) {
                if ( "Nimbus".equals (info.getName ()) ) {
                    javax.swing.UIManager.setLookAndFeel (info.getClassName ());
                    break;
                }
            }
        }
        catch ( ClassNotFoundException ex ) {
            java.util.logging.Logger.getLogger (DialogChooseCollection.class.getName ()).log (java.util.logging.Level.SEVERE, null, ex);
        }
        catch ( InstantiationException ex ) {
            java.util.logging.Logger.getLogger (DialogChooseCollection.class.getName ()).log (java.util.logging.Level.SEVERE, null, ex);
        }
        catch ( IllegalAccessException ex ) {
            java.util.logging.Logger.getLogger (DialogChooseCollection.class.getName ()).log (java.util.logging.Level.SEVERE, null, ex);
        }
        catch ( javax.swing.UnsupportedLookAndFeelException ex ) {
            java.util.logging.Logger.getLogger (DialogChooseCollection.class.getName ()).log (java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater (new Runnable () {
            public void run () {
                DialogChooseCollection dialog = new DialogChooseCollection (new javax.swing.JFrame (), true);
                dialog.addWindowListener (new java.awt.event.WindowAdapter () {
                    @Override
                    public void windowClosing ( java.awt.event.WindowEvent e ) {
                        System.exit (0);
                    }
                });
                dialog.setVisible (true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_choose;
    private javax.swing.JComboBox<String> comboBox_collection;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel label_title;
    private javax.swing.JPanel panel_background;
    private javax.swing.JPanel panel_header;
    private javax.swing.JPanel panel_paddingLeft;
    private javax.swing.JPanel panel_paddingRight;
    private javax.swing.JPanel panel_paddingTop;
    // End of variables declaration//GEN-END:variables
}
