
package project.quiz.maker;

public final class FormMain extends javax.swing.JFrame {

    private DialogChooseCollection dialogChooseCollection;
    private FormCreateQuiz formCreateQuiz;
    private FormViewCollection formViewCollection;
    private FormMyProfile formMyProfile;
    
    private User loggedUser = null;
    
    public FormMain () {
        initComponents ();
    }
    
    public FormMain(User user) {
        this ();
        loggedUser = user;  
        
        setUsernameField ();
        updateRecordFields ();
    }
    
    public User getLoggUser() {
        return loggedUser;
    }
    
    public void setDialogChooseCollectionClosed() {
        this.dialogChooseCollection = null;
    }
    
    public void setFormCreateQuizClosed() {
        this.formCreateQuiz = null;
    }
    
    public void setFormViewCollectionClosed() {
        this.formViewCollection = null;
    }
    
    public void setFormMyProfileClosed() {
        this.formMyProfile = null;
    }
    
    public void setLoggedUser (User loggedUser) {
        this.loggedUser = loggedUser;  
        updateRecordFields();
    }
    
    private void setUsernameField() {
        label_username.setText (loggedUser.getUsername ().toUpperCase ());
    }

    public void updateRecordFields() {
        UserRecord userRecord = loggedUser.getRecordDetail ();
        String totalCorrect = String.format ("%03d", userRecord.getTotalCorrect ());
        String totalIncorrect = String.format ("%03d", userRecord.getTotalIncorrect ());
        
        label_correctAnswer.setText (totalCorrect);
        label_incorrectAnswer.setText (totalIncorrect);
    }
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_Background = new javax.swing.JPanel();
        panel_Header = new javax.swing.JPanel();
        label_Title = new javax.swing.JLabel();
        panel_headerLeft = new javax.swing.JPanel();
        panel_headerRight = new javax.swing.JPanel();
        panel_headerRightPadding = new javax.swing.JPanel();
        label_titleUsername = new javax.swing.JLabel();
        label_username = new javax.swing.JLabel();
        panel_Footer = new javax.swing.JPanel();
        panel_leftFooter = new javax.swing.JPanel();
        panel_rightFooter = new javax.swing.JPanel();
        panel_infoFooter = new javax.swing.JPanel();
        label_correctAnswer = new javax.swing.JLabel();
        label_incorrectAnswer = new javax.swing.JLabel();
        panel_buttonsFooter = new javax.swing.JPanel();
        label_help = new javax.swing.JLabel();
        label_Support = new javax.swing.JLabel();
        label_notification = new javax.swing.JLabel();
        panel_Left = new javax.swing.JPanel();
        panel_Right = new javax.swing.JPanel();
        panel_Center = new javax.swing.JPanel();
        button_takeQuiz = new javax.swing.JButton();
        button_createNewQuestionCollection = new javax.swing.JButton();
        button_viewCollection = new javax.swing.JButton();
        button_myProfile = new javax.swing.JButton();
        panel_bottomCenter = new javax.swing.JPanel();
        panel_topCenter = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HOME");

        panel_Background.setBackground(new java.awt.Color(255, 255, 255));
        panel_Background.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panel_Background.setPreferredSize(new java.awt.Dimension(1080, 720));

        panel_Header.setBackground(new java.awt.Color(20, 10, 37));
        panel_Header.setPreferredSize(new java.awt.Dimension(1080, 250));

        label_Title.setFont(new java.awt.Font("Bahnschrift", 0, 88)); // NOI18N
        label_Title.setForeground(new java.awt.Color(255, 255, 255));
        label_Title.setText("QUIZ MAKER");

        panel_headerLeft.setBackground(new java.awt.Color(20, 10, 37));

        javax.swing.GroupLayout panel_headerLeftLayout = new javax.swing.GroupLayout(panel_headerLeft);
        panel_headerLeft.setLayout(panel_headerLeftLayout);
        panel_headerLeftLayout.setHorizontalGroup(
            panel_headerLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panel_headerLeftLayout.setVerticalGroup(
            panel_headerLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panel_headerRight.setBackground(new java.awt.Color(20, 10, 37));

        panel_headerRightPadding.setBackground(new java.awt.Color(20, 10, 37));
        panel_headerRightPadding.setPreferredSize(new java.awt.Dimension(100, 0));

        javax.swing.GroupLayout panel_headerRightPaddingLayout = new javax.swing.GroupLayout(panel_headerRightPadding);
        panel_headerRightPadding.setLayout(panel_headerRightPaddingLayout);
        panel_headerRightPaddingLayout.setHorizontalGroup(
            panel_headerRightPaddingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panel_headerRightPaddingLayout.setVerticalGroup(
            panel_headerRightPaddingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        label_titleUsername.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        label_titleUsername.setForeground(new java.awt.Color(255, 255, 255));
        label_titleUsername.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        label_titleUsername.setText("username");

        label_username.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        label_username.setForeground(new java.awt.Color(255, 255, 255));
        label_username.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        label_username.setText("EXAMPLE");

        javax.swing.GroupLayout panel_headerRightLayout = new javax.swing.GroupLayout(panel_headerRight);
        panel_headerRight.setLayout(panel_headerRightLayout);
        panel_headerRightLayout.setHorizontalGroup(
            panel_headerRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_headerRightLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel_headerRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_titleUsername, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_username, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel_headerRightPadding, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panel_headerRightLayout.setVerticalGroup(
            panel_headerRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_headerRightLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_headerRightPadding, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panel_headerRightLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(label_titleUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_username, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panel_HeaderLayout = new javax.swing.GroupLayout(panel_Header);
        panel_Header.setLayout(panel_HeaderLayout);
        panel_HeaderLayout.setHorizontalGroup(
            panel_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_HeaderLayout.createSequentialGroup()
                .addComponent(panel_headerLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label_Title, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel_headerRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_HeaderLayout.setVerticalGroup(
            panel_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label_Title, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                    .addComponent(panel_headerLeft, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(panel_headerRight, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panel_Footer.setBackground(new java.awt.Color(20, 10, 37));

        panel_leftFooter.setBackground(new java.awt.Color(20, 10, 37));
        panel_leftFooter.setPreferredSize(new java.awt.Dimension(100, 35));

        javax.swing.GroupLayout panel_leftFooterLayout = new javax.swing.GroupLayout(panel_leftFooter);
        panel_leftFooter.setLayout(panel_leftFooterLayout);
        panel_leftFooterLayout.setHorizontalGroup(
            panel_leftFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panel_leftFooterLayout.setVerticalGroup(
            panel_leftFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        panel_rightFooter.setBackground(new java.awt.Color(20, 10, 37));

        javax.swing.GroupLayout panel_rightFooterLayout = new javax.swing.GroupLayout(panel_rightFooter);
        panel_rightFooter.setLayout(panel_rightFooterLayout);
        panel_rightFooterLayout.setHorizontalGroup(
            panel_rightFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panel_rightFooterLayout.setVerticalGroup(
            panel_rightFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panel_infoFooter.setBackground(new java.awt.Color(20, 10, 37));
        panel_infoFooter.setLayout(new java.awt.GridLayout(1, 2));

        label_correctAnswer.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        label_correctAnswer.setForeground(new java.awt.Color(255, 255, 255));
        label_correctAnswer.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label_correctAnswer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_ok_20px.png"))); // NOI18N
        label_correctAnswer.setText("000");
        panel_infoFooter.add(label_correctAnswer);

        label_incorrectAnswer.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        label_incorrectAnswer.setForeground(new java.awt.Color(255, 255, 255));
        label_incorrectAnswer.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label_incorrectAnswer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_cancel_20px.png"))); // NOI18N
        label_incorrectAnswer.setText("000");
        panel_infoFooter.add(label_incorrectAnswer);

        panel_buttonsFooter.setBackground(new java.awt.Color(20, 10, 37));
        panel_buttonsFooter.setLayout(new java.awt.GridLayout(1, 3));

        label_help.setForeground(new java.awt.Color(255, 255, 255));
        label_help.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        label_help.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_help_25px.png"))); // NOI18N
        panel_buttonsFooter.add(label_help);

        label_Support.setForeground(new java.awt.Color(255, 255, 255));
        label_Support.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        label_Support.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_happy_25px.png"))); // NOI18N
        label_Support.setToolTipText("");
        panel_buttonsFooter.add(label_Support);

        label_notification.setForeground(new java.awt.Color(255, 255, 255));
        label_notification.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        label_notification.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_notification_25px.png"))); // NOI18N
        panel_buttonsFooter.add(label_notification);

        javax.swing.GroupLayout panel_FooterLayout = new javax.swing.GroupLayout(panel_Footer);
        panel_Footer.setLayout(panel_FooterLayout);
        panel_FooterLayout.setHorizontalGroup(
            panel_FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_FooterLayout.createSequentialGroup()
                .addComponent(panel_leftFooter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_infoFooter, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panel_buttonsFooter, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel_rightFooter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panel_FooterLayout.setVerticalGroup(
            panel_FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_FooterLayout.createSequentialGroup()
                .addComponent(panel_leftFooter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(panel_rightFooter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panel_infoFooter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panel_buttonsFooter, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panel_Left.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panel_LeftLayout = new javax.swing.GroupLayout(panel_Left);
        panel_Left.setLayout(panel_LeftLayout);
        panel_LeftLayout.setHorizontalGroup(
            panel_LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panel_LeftLayout.setVerticalGroup(
            panel_LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panel_Right.setBackground(new java.awt.Color(255, 255, 255));
        panel_Right.setPreferredSize(new java.awt.Dimension(100, 0));

        javax.swing.GroupLayout panel_RightLayout = new javax.swing.GroupLayout(panel_Right);
        panel_Right.setLayout(panel_RightLayout);
        panel_RightLayout.setHorizontalGroup(
            panel_RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panel_RightLayout.setVerticalGroup(
            panel_RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panel_Center.setBackground(new java.awt.Color(255, 255, 255));
        panel_Center.setLayout(new java.awt.GridLayout(2, 3, 20, 20));

        button_takeQuiz.setUI(new CSSButton ());
        button_takeQuiz.setBackground(new java.awt.Color(219, 43, 48));
        button_takeQuiz.setFont(new java.awt.Font("Bahnschrift", 0, 22)); // NOI18N
        button_takeQuiz.setForeground(new java.awt.Color(255, 255, 255));
        button_takeQuiz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_test_passed_96px.png"))); // NOI18N
        button_takeQuiz.setText("take a quiz");
        button_takeQuiz.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        button_takeQuiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_takeQuizActionPerformed(evt);
            }
        });
        panel_Center.add(button_takeQuiz);

        button_createNewQuestionCollection.setUI(new CSSButton ());
        button_createNewQuestionCollection.setBackground(new java.awt.Color(219, 43, 48));
        button_createNewQuestionCollection.setFont(new java.awt.Font("Bahnschrift", 0, 22)); // NOI18N
        button_createNewQuestionCollection.setForeground(new java.awt.Color(255, 255, 255));
        button_createNewQuestionCollection.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_create_96px.png"))); // NOI18N
        button_createNewQuestionCollection.setText("<html>create<br>new quiz<br>collection</html>");
        button_createNewQuestionCollection.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        button_createNewQuestionCollection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_createNewQuestionCollectionActionPerformed(evt);
            }
        });
        panel_Center.add(button_createNewQuestionCollection);

        button_viewCollection.setUI(new CSSButton ());
        button_viewCollection.setBackground(new java.awt.Color(219, 43, 48));
        button_viewCollection.setFont(new java.awt.Font("Bahnschrift", 0, 22)); // NOI18N
        button_viewCollection.setForeground(new java.awt.Color(255, 255, 255));
        button_viewCollection.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_view_96px.png"))); // NOI18N
        button_viewCollection.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        button_viewCollection.setLabel("view collection");
        button_viewCollection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_viewCollectionActionPerformed(evt);
            }
        });
        panel_Center.add(button_viewCollection);

        button_myProfile.setUI(new CSSButton ());
        button_myProfile.setBackground(new java.awt.Color(219, 43, 48));
        button_myProfile.setFont(new java.awt.Font("Bahnschrift", 0, 22)); // NOI18N
        button_myProfile.setForeground(new java.awt.Color(255, 255, 255));
        button_myProfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_contact_details_96px.png"))); // NOI18N
        button_myProfile.setText("my profile");
        button_myProfile.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        button_myProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_myProfileActionPerformed(evt);
            }
        });
        panel_Center.add(button_myProfile);

        panel_bottomCenter.setBackground(new java.awt.Color(255, 255, 255));
        panel_bottomCenter.setPreferredSize(new java.awt.Dimension(0, 20));

        javax.swing.GroupLayout panel_bottomCenterLayout = new javax.swing.GroupLayout(panel_bottomCenter);
        panel_bottomCenter.setLayout(panel_bottomCenterLayout);
        panel_bottomCenterLayout.setHorizontalGroup(
            panel_bottomCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panel_bottomCenterLayout.setVerticalGroup(
            panel_bottomCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        panel_topCenter.setBackground(new java.awt.Color(255, 255, 255));
        panel_topCenter.setPreferredSize(new java.awt.Dimension(0, 20));

        javax.swing.GroupLayout panel_topCenterLayout = new javax.swing.GroupLayout(panel_topCenter);
        panel_topCenter.setLayout(panel_topCenterLayout);
        panel_topCenterLayout.setHorizontalGroup(
            panel_topCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panel_topCenterLayout.setVerticalGroup(
            panel_topCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panel_BackgroundLayout = new javax.swing.GroupLayout(panel_Background);
        panel_Background.setLayout(panel_BackgroundLayout);
        panel_BackgroundLayout.setHorizontalGroup(
            panel_BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_Header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panel_Footer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel_BackgroundLayout.createSequentialGroup()
                .addComponent(panel_Left, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_bottomCenter, javax.swing.GroupLayout.DEFAULT_SIZE, 868, Short.MAX_VALUE)
                    .addComponent(panel_Center, javax.swing.GroupLayout.DEFAULT_SIZE, 868, Short.MAX_VALUE)
                    .addComponent(panel_topCenter, javax.swing.GroupLayout.DEFAULT_SIZE, 868, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_Right, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panel_BackgroundLayout.setVerticalGroup(
            panel_BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_BackgroundLayout.createSequentialGroup()
                .addComponent(panel_Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_Left, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panel_BackgroundLayout.createSequentialGroup()
                        .addComponent(panel_topCenter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panel_Center, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panel_bottomCenter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panel_Right, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_Footer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void button_takeQuizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_takeQuizActionPerformed
        if (!VerifyVariable.hasDialogOpened (dialogChooseCollection)) {
           dialogChooseCollection = new DialogChooseCollection (null, true, this);           
           dialogChooseCollection.setVisible (true);
       }
    }//GEN-LAST:event_button_takeQuizActionPerformed

    private void button_createNewQuestionCollectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_createNewQuestionCollectionActionPerformed
       if(!VerifyVariable.hasFormOpened (formCreateQuiz)) {
            formCreateQuiz = new FormCreateQuiz (this);
            formCreateQuiz.setVisible(true);
        }
    }//GEN-LAST:event_button_createNewQuestionCollectionActionPerformed

    private void button_viewCollectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_viewCollectionActionPerformed
        if(!VerifyVariable.hasFormOpened (formViewCollection)) {
            formViewCollection = new FormViewCollection (this);
            formViewCollection.setVisible(true);
        }
    }//GEN-LAST:event_button_viewCollectionActionPerformed

    private void button_myProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_myProfileActionPerformed
        if (!VerifyVariable.hasFormOpened (formMyProfile)) {
            formMyProfile = new FormMyProfile (this);
            formMyProfile.setVisible (true);
        }
    }//GEN-LAST:event_button_myProfileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main ( String args[] ) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for ( javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels () ) {
                if ( "Nimbus".equals (info.getName ()) ) {
                    javax.swing.UIManager.setLookAndFeel (info.getClassName ());
                    break;
                }
            }
        }
        catch ( ClassNotFoundException ex ) {
            java.util.logging.Logger.getLogger (FormMain.class.getName ()).log (java.util.logging.Level.SEVERE, null, ex);
        }
        catch ( InstantiationException ex ) {
            java.util.logging.Logger.getLogger (FormMain.class.getName ()).log (java.util.logging.Level.SEVERE, null, ex);
        }
        catch ( IllegalAccessException ex ) {
            java.util.logging.Logger.getLogger (FormMain.class.getName ()).log (java.util.logging.Level.SEVERE, null, ex);
        }
        catch ( javax.swing.UnsupportedLookAndFeelException ex ) {
            java.util.logging.Logger.getLogger (FormMain.class.getName ()).log (java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        
        DialogLogin dialogLogin = new DialogLogin (null, true);
        dialogLogin.setVisible (true);
        
        boolean isAllowed = dialogLogin.getAccessAllowed ();
        
        if (isAllowed) {
            dialogLogin.dispose ();
            
            User loggedUser = dialogLogin.getLoggingUser ();
            
            java.awt.EventQueue.invokeLater (new Runnable () {
                public void run () {
                    new FormMain (loggedUser).setVisible (true);
                }
            });
        } 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_createNewQuestionCollection;
    private javax.swing.JButton button_myProfile;
    private javax.swing.JButton button_takeQuiz;
    private javax.swing.JButton button_viewCollection;
    private javax.swing.JLabel label_Support;
    private javax.swing.JLabel label_Title;
    private javax.swing.JLabel label_correctAnswer;
    private javax.swing.JLabel label_help;
    private javax.swing.JLabel label_incorrectAnswer;
    private javax.swing.JLabel label_notification;
    private javax.swing.JLabel label_titleUsername;
    private javax.swing.JLabel label_username;
    private javax.swing.JPanel panel_Background;
    private javax.swing.JPanel panel_Center;
    private javax.swing.JPanel panel_Footer;
    private javax.swing.JPanel panel_Header;
    private javax.swing.JPanel panel_Left;
    private javax.swing.JPanel panel_Right;
    private javax.swing.JPanel panel_bottomCenter;
    private javax.swing.JPanel panel_buttonsFooter;
    private javax.swing.JPanel panel_headerLeft;
    private javax.swing.JPanel panel_headerRight;
    private javax.swing.JPanel panel_headerRightPadding;
    private javax.swing.JPanel panel_infoFooter;
    private javax.swing.JPanel panel_leftFooter;
    private javax.swing.JPanel panel_rightFooter;
    private javax.swing.JPanel panel_topCenter;
    // End of variables declaration//GEN-END:variables
}
