
package project.quiz.maker;

import java.time.Duration;
import java.time.Instant;
import java.util.LinkedList;
import java.util.Map;

public final class FormTakeQuiz extends javax.swing.JFrame {

    private final UserData userData = UserData.createInstance ();
    
    private DialogChooseCollection dialogChooseCollection = null;
    private DialogTestResult dialogTestResult = null;
    
    private Map<Integer, User> map;
    private User loggedUser;
    private LinkedList<Question> questions;
    private Question currentQuestion;
    
    private int currentIndex = 0;
    private int counterCorrect = 0;
    private int totalQuestion = 0;
    private double averageSpeed = 0;
    
    private Instant startTime;
    private Instant endTime;
    private long timeElapsed = 0;
      
    public FormTakeQuiz () {
        initComponents ();
    }
    
    public FormTakeQuiz(Collection selectedCollection) {
        this();    
        this.questions = selectedCollection.getQuestionList ();
        this.totalQuestion = selectedCollection.getTotalQuestion ();
                
        setRelatedData ();
        setStartTime ();
    }
    
    public FormTakeQuiz(DialogChooseCollection dialogChooseCollection, Collection selectedCollection) {
        this (selectedCollection);
        this.dialogChooseCollection = dialogChooseCollection;
    }
    
    public void setLoggedUser(User loggedUser) {
        this.loggedUser = loggedUser;
    }
    
    private void setStartTime() {
        startTime = Instant.now ();
    }
    
    private void setEndTime() {
        endTime = Instant.now ();
        
        timeElapsed = Duration.between (startTime, endTime).toMillis () / 1000;
        averageSpeed = totalQuestion / (timeElapsed/60.0); // QPM
        averageSpeed = FormatValue.formatAverage (averageSpeed);
    }
    
    private void setRelatedData() {
        setQuestionData();
        setCounterQuestion ();
        setTotalCorrect ();
              
        if(isLastQuestion())
            setButtonTextToViewResult ();
    }
    
    private void setQuestionData() {
        currentQuestion = questions.get (currentIndex);
        
        textarea_question.setText (currentQuestion.getQuestionDetail ());
        
        panel_answers.removeAllAnswers ();
        LinkedList<Answer> answers = currentQuestion.getAnswerList ();
        for ( int i = answers.size () -1  ; i >= 0  ; i-- ) {
            Answer value = answers.get (i);
            
            AnswerControl answer = new AnswerControl (value.getAnswerDetail (), false);
            answer.setAnswerEditable (false);
            
            panel_answers.addAnswer (answer);
        }
    }
    
    private void setCounterQuestion () {
        String count = (currentIndex+1) + "/" + totalQuestion;
        label_countQuestion.setText (count);
    }
    
    private void setTotalCorrect() {
        String count = counterCorrect + "/" + totalQuestion;
        label_score.setText("total score : " + count);
    }
    
    private void setButtonTextToViewResult() {
        button_next.setText ("VIEW RESULT");
    }
    
    private boolean isLastQuestion() {
        return (currentIndex == totalQuestion-1);
    }
    
    private void updateRecordData() {
        UserRecord userRecord = loggedUser.getRecordDetail ();
        userRecord.increaseTotalCorrect (counterCorrect);
        userRecord.increaseTotalQuestion (totalQuestion);
        userRecord.setTotalIncorrect ();
        userRecord.setAverageSpeed (averageSpeed);
        userRecord.setRecentRecord (counterCorrect + "/" + totalQuestion);
    }
    
    private void loadDialogResult() {
        Result result = new Result (totalQuestion, counterCorrect, totalQuestion - counterCorrect, averageSpeed);
        dialogTestResult = new DialogTestResult (null, false, result);
        dialogTestResult.setVisible (true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_background = new javax.swing.JPanel();
        panel_header = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        label_title = new javax.swing.JLabel();
        panel_leftPadding = new javax.swing.JPanel();
        panel_rightPadding = new javax.swing.JPanel();
        panel_topPadding = new javax.swing.JPanel();
        panel_question = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textarea_question = new javax.swing.JTextArea();
        label_collection = new javax.swing.JLabel();
        label_countQuestion = new javax.swing.JLabel();
        panel_answer = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        panel_answers = new project.quiz.maker.PanelAnswer();
        panel_footer = new javax.swing.JPanel();
        button_next = new javax.swing.JButton();
        label_score = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("TAKING TEST");
        setAlwaysOnTop(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        panel_background.setBackground(new java.awt.Color(255, 255, 255));

        panel_header.setBackground(new java.awt.Color(20, 10, 37));

        jPanel2.setBackground(new java.awt.Color(20, 10, 37));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(20, 10, 37));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        label_title.setFont(new java.awt.Font("Bahnschrift", 0, 36)); // NOI18N
        label_title.setForeground(new java.awt.Color(255, 255, 255));
        label_title.setText("TAKING TEST");
        label_title.setToolTipText("");

        javax.swing.GroupLayout panel_headerLayout = new javax.swing.GroupLayout(panel_header);
        panel_header.setLayout(panel_headerLayout);
        panel_headerLayout.setHorizontalGroup(
            panel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_headerLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panel_headerLayout.setVerticalGroup(
            panel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_headerLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_title, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        panel_leftPadding.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panel_leftPaddingLayout = new javax.swing.GroupLayout(panel_leftPadding);
        panel_leftPadding.setLayout(panel_leftPaddingLayout);
        panel_leftPaddingLayout.setHorizontalGroup(
            panel_leftPaddingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );
        panel_leftPaddingLayout.setVerticalGroup(
            panel_leftPaddingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panel_rightPadding.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panel_rightPaddingLayout = new javax.swing.GroupLayout(panel_rightPadding);
        panel_rightPadding.setLayout(panel_rightPaddingLayout);
        panel_rightPaddingLayout.setHorizontalGroup(
            panel_rightPaddingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );
        panel_rightPaddingLayout.setVerticalGroup(
            panel_rightPaddingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panel_topPadding.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panel_topPaddingLayout = new javax.swing.GroupLayout(panel_topPadding);
        panel_topPadding.setLayout(panel_topPaddingLayout);
        panel_topPaddingLayout.setHorizontalGroup(
            panel_topPaddingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panel_topPaddingLayout.setVerticalGroup(
            panel_topPaddingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        panel_question.setBackground(new java.awt.Color(255, 255, 255));
        panel_question.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "READ THE QUESTION CAREFULLY", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bahnschrift", 0, 18))); // NOI18N

        textarea_question.setEditable(false);
        textarea_question.setColumns(20);
        textarea_question.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        textarea_question.setRows(5);
        textarea_question.setFocusable(false);
        jScrollPane1.setViewportView(textarea_question);

        label_collection.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        label_collection.setText("question number");
        label_collection.setToolTipText("");

        label_countQuestion.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        label_countQuestion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_countQuestion.setText("0/0");

        javax.swing.GroupLayout panel_questionLayout = new javax.swing.GroupLayout(panel_question);
        panel_question.setLayout(panel_questionLayout);
        panel_questionLayout.setHorizontalGroup(
            panel_questionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_questionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_questionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label_collection, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label_countQuestion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        panel_questionLayout.setVerticalGroup(
            panel_questionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_questionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_questionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(panel_questionLayout.createSequentialGroup()
                        .addComponent(label_collection, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_countQuestion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        panel_answer.setBackground(new java.awt.Color(255, 255, 255));
        panel_answer.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CHOOSE ONE OR MORE ANSWERS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bahnschrift", 0, 18))); // NOI18N

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setPreferredSize(new java.awt.Dimension(222, 0));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 222, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setPreferredSize(new java.awt.Dimension(222, 0));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 222, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panel_answerLayout = new javax.swing.GroupLayout(panel_answer);
        panel_answer.setLayout(panel_answerLayout);
        panel_answerLayout.setHorizontalGroup(
            panel_answerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_answerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_answers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panel_answerLayout.setVerticalGroup(
            panel_answerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_answerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_answerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                    .addComponent(panel_answers, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE))
                .addContainerGap())
        );

        panel_footer.setBackground(new java.awt.Color(255, 255, 255));
        panel_footer.setPreferredSize(new java.awt.Dimension(100, 66));

        button_next.setUI(new CSSButton());
        button_next.setBackground(new java.awt.Color(219, 43, 48));
        button_next.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        button_next.setForeground(new java.awt.Color(255, 255, 255));
        button_next.setText("NEXT");
        button_next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_nextActionPerformed(evt);
            }
        });

        label_score.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        label_score.setText("total score : ");
        label_score.setToolTipText("");

        javax.swing.GroupLayout panel_footerLayout = new javax.swing.GroupLayout(panel_footer);
        panel_footer.setLayout(panel_footerLayout);
        panel_footerLayout.setHorizontalGroup(
            panel_footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_footerLayout.createSequentialGroup()
                .addComponent(label_score, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(button_next, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panel_footerLayout.setVerticalGroup(
            panel_footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_footerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel_footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_next, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_score, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout panel_backgroundLayout = new javax.swing.GroupLayout(panel_background);
        panel_background.setLayout(panel_backgroundLayout);
        panel_backgroundLayout.setHorizontalGroup(
            panel_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel_backgroundLayout.createSequentialGroup()
                .addComponent(panel_leftPadding, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_topPadding, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_answer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_footer, javax.swing.GroupLayout.DEFAULT_SIZE, 918, Short.MAX_VALUE)
                    .addComponent(panel_question, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_rightPadding, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panel_backgroundLayout.setVerticalGroup(
            panel_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_backgroundLayout.createSequentialGroup()
                .addComponent(panel_header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_backgroundLayout.createSequentialGroup()
                        .addComponent(panel_topPadding, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panel_question, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panel_answer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panel_footer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panel_rightPadding, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_leftPadding, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void button_nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_nextActionPerformed
        String questionAnswer = currentQuestion.getAllChosenNO ();
        String userAnswer = panel_answers.getAllChosenNO ();
        
        boolean hasUserChosenCorrectAnswer = questionAnswer.equals (userAnswer);
        if(hasUserChosenCorrectAnswer) {
            counterCorrect++;
        }
        
        currentIndex ++;
        
        boolean isViewResult = button_next.getText ().equals ("VIEW RESULT");
        if(!isViewResult)
            setRelatedData ();
        else {
            setEndTime ();
            
            setTotalCorrect ();
            
            if(loggedUser != null) {
                map = userData.fetchMapData ();
                
                boolean foundUser = map.containsKey (loggedUser.getUserID ());
                
                if(foundUser) {
                    updateRecordData();
                    
                    map.put (loggedUser.getUserID (), loggedUser);
                    userData.commitMapData (map, "");
                    
                    dialogChooseCollection.updateFormMainData (loggedUser);
                }
            }
            
            loadDialogResult();
            
            this.dispose ();
        }
    }//GEN-LAST:event_button_nextActionPerformed
    
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if(VerifyVariable.hasDialogOpened (dialogChooseCollection)) {
            dialogChooseCollection.setFormTakeQuizClosed ();
            dialogChooseCollection.setDialogChooseCollectionClosed();
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main ( String args[] ) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for ( javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels () ) {
                if ( "Nimbus".equals (info.getName ()) ) {
                    javax.swing.UIManager.setLookAndFeel (info.getClassName ());
                    break;
                }
            }
        }
        catch ( ClassNotFoundException ex ) {
            java.util.logging.Logger.getLogger (FormTakeQuiz.class.getName ()).log (java.util.logging.Level.SEVERE, null, ex);
        }
        catch ( InstantiationException ex ) {
            java.util.logging.Logger.getLogger (FormTakeQuiz.class.getName ()).log (java.util.logging.Level.SEVERE, null, ex);
        }
        catch ( IllegalAccessException ex ) {
            java.util.logging.Logger.getLogger (FormTakeQuiz.class.getName ()).log (java.util.logging.Level.SEVERE, null, ex);
        }
        catch ( javax.swing.UnsupportedLookAndFeelException ex ) {
            java.util.logging.Logger.getLogger (FormTakeQuiz.class.getName ()).log (java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        DialogChooseCollection dialogChooseCollection = new DialogChooseCollection (null, true);
        dialogChooseCollection.setVisible (true);
        
        boolean hasSelected = dialogChooseCollection.hasSelectedCollection();
        
        if(hasSelected) {
            dialogChooseCollection.dispose ();
        
            Collection selectedCollection = dialogChooseCollection.getSelectedCollection();
            boolean isCollectionEmpty = selectedCollection.getQuestionList ().isEmpty ();
            
            if(!isCollectionEmpty) {   
                java.awt.EventQueue.invokeLater (new Runnable () {
                    public void run () {
                        new FormTakeQuiz (selectedCollection).setVisible (true);
                    }
                });
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_next;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_collection;
    private javax.swing.JLabel label_countQuestion;
    private javax.swing.JLabel label_score;
    private javax.swing.JLabel label_title;
    private javax.swing.JPanel panel_answer;
    private project.quiz.maker.PanelAnswer panel_answers;
    private javax.swing.JPanel panel_background;
    private javax.swing.JPanel panel_footer;
    private javax.swing.JPanel panel_header;
    private javax.swing.JPanel panel_leftPadding;
    private javax.swing.JPanel panel_question;
    private javax.swing.JPanel panel_rightPadding;
    private javax.swing.JPanel panel_topPadding;
    private javax.swing.JTextArea textarea_question;
    // End of variables declaration//GEN-END:variables
}
